/** Projetos em destaque na landing (portfólio da YOP Devs).
 *
 * Logos: public/projetos/{key}.png|.webp (fenix e yopdevs têm caminhos próprios)
 * Prints: public/projetos/prints/ — usados na secção de cases
 */
export const FEATURED_PROJECTS = [
  {
    key: 'plify',
    name: 'Plify 360',
    short: 'Plify',
    tag: 'SaaS',
    description:
      'ERP/SaaS para PMEs: propostas, clientes, financeiro, WhatsApp, IA e pagamentos com Stripe.',
    href: 'https://plify360.com.br',
    logo: '/projetos/plify/logo.png?v=3',
    image: '/projetos/prints/plify.png?v=2',
    print: '/projetos/prints/plify.png?v=2',
    gallery: [
      '/projetos/prints/plify.png?v=2',
      '/projetos/prints/plify/safe/landing.png',
      '/projetos/prints/plify/safe/dashboard.png',
      '/projetos/prints/plify/safe/propostas.png',
      '/projetos/prints/plify/safe/agenda.png',
      '/projetos/prints/plify/safe/mapa.png',
      '/projetos/prints/plify/safe/contratos.png',
      '/projetos/prints/plify/safe/signup.png',
    ],
  },
  {
    key: 'westham',
    name: 'Westham Sport Club',
    short: 'Westham',
    tag: 'Gestão esportiva',
    description:
      'Site e painel do clube: notícias, jogos (FUT11, Fut7 e Futsal), projetos, sócios, loja, jogadores e caixa, tudo gerido num admin completo.',
    href: 'https://www.farrus.com.br/',
    logo: '/projetos/westham/logo.png?v=2',
    image: '/projetos/prints/westham.png?v=1',
    print: '/projetos/prints/westham.png?v=1',
    gallery: [
      '/projetos/prints/westham.png?v=1',
      '/projetos/prints/westham/safe/home.png',
      '/projetos/prints/westham/safe/projetos.png',
      '/projetos/prints/westham/safe/jogos.png',
      '/projetos/prints/westham/safe/admin-home.png',
      '/projetos/prints/westham/safe/admin-jogadores.png',
      '/projetos/prints/westham/safe/admin-noticias.png',
      '/projetos/prints/westham/safe/admin-jogos.png',
      '/projetos/prints/westham/safe/admin-users.png',
    ],
  },
  {
    key: 'palha',
    name: 'Palha Weddings',
    short: 'Palha',
    tag: 'Álbuns & eventos',
    description:
      'Sistema para anexar fotos e vídeos de casamentos, aniversários e eventos: álbuns com senha, reprodução e download de mídias, grades de exposição e página inicial 100% editável pelo admin.',
    href: 'https://palhaweddings.plify360.com.br/',
    logo: '/projetos/palha/logo.png?v=2',
    image: '/projetos/prints/palha.png?v=2',
    print: '/projetos/prints/palha.png?v=2',
    gallery: [
      '/projetos/prints/palha.png?v=2',
      '/projetos/prints/palha/safe/home.png',
      '/projetos/prints/palha/safe/landing.png',
      '/projetos/prints/palha/safe/albuns.png',
      '/projetos/prints/palha/safe/login.png',
      '/projetos/prints/palha/safe/admin-home.png',
      '/projetos/prints/palha/safe/admin-galeria.png',
      '/projetos/prints/palha/safe/admin-dados.png',
    ],
  },
  {
    key: 'fenix',
    name: 'Fênix Gestora',
    short: 'Fênix',
    tag: 'Consórcios',
    description:
      'Sistema para empresas representantes de consórcios: CRM, ranking, processos, cartas contempladas e vendas. Integrações com Playwright para envio automático de boletos e oferta de lances fixos.',
    href: 'https://www.fenixgestora.com.br',
    logo: '/projetos/fenix/logo.420a748b9c9c09dc115e.png',
    image: '/projetos/prints/fenix.png?v=4',
    print: '/projetos/prints/fenix.png?v=4',
    gallery: [
      '/projetos/prints/fenix.png?v=4',
      '/projetos/prints/fenix/safe/inicial.png',
      '/projetos/prints/fenix/safe/vendas.png',
      '/projetos/prints/fenix/safe/crm.png',
      '/projetos/prints/fenix/safe/ranking.png',
      '/projetos/prints/fenix/safe/processos.png',
      '/projetos/prints/fenix/safe/cartas.png',
      '/projetos/prints/fenix/safe/docs.png',
      '/projetos/prints/fenix/safe/login.png',
    ],
  },
  {
    key: 'teuposto',
    name: 'Teu Posto',
    short: 'Teu Posto',
    tag: 'Postos de combustível',
    description:
      'Plataforma para donos e gerentes de postos: análises de combustíveis, verificação metrológica, documentos com avisos de vencimento, WhatsApp, Mercado Pago, liberações automáticas e página pública para clientes acompanharem os RAQs.',
    href: 'https://www.appteuposto.com.br/',
    logo: '/projetos/teuposto/logo.png?v=2',
    image: '/projetos/prints/teuposto.png?v=1',
    print: '/projetos/prints/teuposto.png?v=1',
    gallery: [
      '/projetos/prints/teuposto.png?v=1',
      '/projetos/prints/teuposto/safe/login.png',
      '/projetos/prints/teuposto/safe/home.png',
      '/projetos/prints/teuposto/safe/documentos.png',
      '/projetos/prints/teuposto/safe/raq.png',
      '/projetos/prints/teuposto/safe/metrologia.png',
      '/projetos/prints/teuposto/safe/drenagens.png',
      '/projetos/prints/teuposto/safe/seguranca.png',
      '/projetos/prints/teuposto/safe/cadastro.png',
      '/projetos/prints/teuposto/safe/publico.png',
    ],
  },
  {
    key: 'meb',
    name: 'M&B Transportes',
    short: 'M&B',
    tag: 'Transporte & frota',
    description:
      'Gestão de frota própria e de terceiros: motoristas, viagens, financeiro, documentação com avisos de vencimento e relatórios.',
    href: 'https://www.mebtransporte.com.br/',
    logo: '/projetos/meb/logo.png?v=3',
    image: '/projetos/prints/meb.png?v=2',
    print: '/projetos/prints/meb.png?v=2',
    gallery: [
      '/projetos/prints/meb.png?v=2',
      '/projetos/prints/meb/safe/login.png',
      '/projetos/prints/meb/safe/dashboard.png',
      '/projetos/prints/meb/safe/acompanhamento.png',
      '/projetos/prints/meb/safe/viagens.png',
      '/projetos/prints/meb/safe/manutencao.png',
      '/projetos/prints/meb/safe/documentacao.png',
      '/projetos/prints/meb/safe/veiculos.png',
      '/projetos/prints/meb/safe/financeiro.png',
      '/projetos/prints/meb/safe/recebimentos.png',
    ],
  },
  {
    key: 'toq',
    name: 'TOQ Tennis',
    short: 'TOQ',
    tag: 'Rede social & tênis',
    description:
      'Rede social de tênis com gestão de quadras, clubes, comunidades, torneios, aulas, chat e planos com pagamento automático.',
    href: 'https://www.toqtennis.com.br/',
    logo: '/projetos/toq/logo.png?v=2',
    image: '/projetos/prints/toq.png?v=2',
    print: '/projetos/prints/toq.png?v=2',
    gallery: [
      '/projetos/prints/toq.png?v=2',
      '/projetos/prints/toq/safe/feed.png',
      '/projetos/prints/toq/safe/comunidade.png',
      '/projetos/prints/toq/safe/mensagens.png',
      '/projetos/prints/toq/safe/clube.png',
      '/projetos/prints/toq/safe/quadras.png',
      '/projetos/prints/toq/safe/torneios.png',
      '/projetos/prints/toq/safe/aulas.png',
      '/projetos/prints/toq/safe/gestao-quadras.png',
      '/projetos/prints/toq/safe/perfil.png',
    ],
  },
  {
    key: 'demolay',
    name: 'Capítulo 862 da Ordem DeMolay',
    short: 'DeMolay',
    tag: 'Institucional',
    description:
      'Sistema completo do capítulo: site público, área do membro, painel admin, usuários, finanças, atas, frequência, candidaturas, notícias, calendário, selos e sorteios com venda de números de rifa.',
    href: 'https://www.demolay862.com.br/',
    logo: '/projetos/demolay/logo.png?v=2',
    image: '/projetos/prints/demolay.png?v=1',
    print: '/projetos/prints/demolay.png?v=1',
    gallery: [
      '/projetos/prints/demolay.png?v=1',
      '/projetos/prints/demolay/safe/home.png',
      '/projetos/prints/demolay/safe/membros.png',
      '/projetos/prints/demolay/safe/noticias.png',
      '/projetos/prints/demolay/safe/sorteios.png',
      '/projetos/prints/demolay/safe/login.png',
      '/projetos/prints/demolay/safe/admin-painel.png',
      '/projetos/prints/demolay/safe/admin-financas.png',
      '/projetos/prints/demolay/safe/admin-atas.png',
      '/projetos/prints/demolay/safe/admin-candidaturas.png',
      '/projetos/prints/demolay/safe/admin-calendario.png',
      '/projetos/prints/demolay/safe/admin-frequencia.png',
    ],
  },
] as const

export type FeaturedProject = (typeof FEATURED_PROJECTS)[number] & {
  gallery?: readonly string[]
}

export const SERVICES = [
  {
    label: 'Sites institucionais',
    icon: 'globe',
    accent: 'cyan',
    description: 'Presença digital clara, rápida e alinhada à marca, com conversão e SEO de base.',
    detail:
      'Criamos o site da sua empresa como canal de confiança e geração de leads: identidade visual forte, páginas rápidas, conteúdo estruturado e formulários que convertem. Ideal para apresentar serviços, cases e facilitar o primeiro contacto com o cliente.',
    points: [
      'Design alinhado à marca e responsivo',
      'Performance, SEO técnico e Core Web Vitals',
      'Formulários, CTAs e integração com WhatsApp',
      'Painel simples para atualizar conteúdos',
    ],
  },
  {
    label: 'Sistemas web',
    icon: 'code',
    accent: 'violet',
    description: 'Painéis e plataformas sob medida para operação, vendas, CRM e gestão em escala.',
    detail:
      'Desenvolvemos plataformas internas e produtos SaaS que organizam a operação do dia a dia: CRM, vendas, financeiro, ranking, processos e relatórios. Tudo com permissões por utilizador, dados em tempo real e arquitetura preparada para crescer com o negócio.',
    points: [
      'CRM, vendas, ranking e processos',
      'Dashboards e relatórios em tempo real',
      'Multi-usuário, filiais e permissões',
      'APIs, autenticação e base PostgreSQL',
    ],
  },
  {
    label: 'Aplicações personalizadas',
    icon: 'mobile',
    accent: 'fuchsia',
    description: 'Produtos digitais e PWAs pensados para o fluxo real do utilizador e do negócio.',
    detail:
      'Construímos aplicações sob medida (web apps e PWAs) quando o fluxo do negócio não cabe num template. Do onboarding ao checkout, desenhamos a experiência à volta do utilizador e ligamos a APIs, pagamentos e automações necessárias.',
    points: [
      'PWA e experiência mobile-first',
      'Fluxos e regras de negócio sob medida',
      'Integração com APIs e gateways',
      'Publicação rápida e evolução contínua',
    ],
  },
  {
    label: 'Automações e integrações',
    icon: 'gear',
    accent: 'amber',
    description: 'Ligações entre sistemas, WhatsApp, pagamentos e rotinas que eliminam trabalho manual.',
    detail:
      'Automatizamos tarefas repetitivas e ligamos os sistemas que a sua empresa já usa. De boletos e lances com Playwright a WhatsApp, pagamentos e sincronização de dados: menos trabalho manual, menos erro e mais escala.',
    points: [
      'Playwright: boletos, lances e rotinas',
      'WhatsApp, Stripe e Mercado Pago',
      'Sincronização entre sistemas e APIs',
      'Alertas, filas e execução sem intervenção',
    ],
  },
] as const

export const TECH_STACK = [
  { name: 'Next.js', slug: 'nextdotjs', color: '000000' },
  { name: 'React', slug: 'react', color: '61DAFB' },
  { name: 'Node.js', slug: 'nodedotjs', color: '339933' },
  { name: 'TypeScript', slug: 'typescript', color: '3178C6' },
  { name: 'Tailwind CSS', slug: 'tailwindcss', color: '06B6D4' },
  { name: 'PostgreSQL', slug: 'postgresql', color: '4169E1' },
  { name: 'Supabase', slug: 'supabase', color: '3FCF8E' },
  { name: 'Vercel', slug: 'vercel', color: '000000' },
  { name: 'Cloudflare', slug: 'cloudflare', color: 'F38020' },
  { name: 'Docker', slug: 'docker', color: '2496ED' },
  { name: 'GitHub', slug: 'github', color: '181717' },
  { name: 'Stripe', slug: 'stripe', color: '635BFF' },
  { name: 'Mercado Pago', slug: 'mercadopago', color: '00B1EA' },
  { name: 'WhatsApp', slug: 'whatsapp', color: '25D366' },
  { name: 'Playwright', slug: 'playwright', color: '2EAD33', local: true },
  { name: 'Python', slug: 'python', color: '3776AB' },
] as const
